databases:
  - name: musoki
    databaseName: kay_and3kay
    user: kay_and3_user
services:
  - type: web
    name: budgetapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: musoki
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false